[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["rm -f tsconfig.tsbuildinfo package-lock.json", "npm install --include=dev --registry=https://registry.npmjs.org/"]

[phases.build]
cmds = ["rm -f tsconfig.tsbuildinfo", "npm run build"]

[start]
cmd = "npm start"
